### ISSUE TITLE
Linux. Error on build. Libcef incompatible 

### ISSUE THREAD

**Issue by zabuTNT** [acristoffers/CEF3SimpleSample#11]
I try to build this project on Linux but it seems there's a problem with the libraries in CEF.
GNU/Linux 4.9.0-1-rt2-MANJARO x86_64

```
Building CEF3SimpleSample::Independente
Building CEF3SimpleSample::Linux
Linking...
/usr/bin/ld: skipping incompatible ../CEF3SimpleSample/CEF/Linux/lib/libcef_dll_wrapper.a when searching for -lcef_dll_wrapper
/usr/bin/ld: cannot find -lcef_dll_wrapper
/usr/bin/ld: skipping incompatible ../CEF3SimpleSample/CEF/Linux/lib/libcef.so when searching for -lcef
/usr/bin/ld: cannot find -lcef
collect2: error: ld returned 1 exit status
Copying files around...
mv: cannot stat 'CEF3SimpleSample': No such file or directory
```

How can I fix this? Thank you for the info.

**Comment by acristoffers** [comment]
I don't know what's wrong, it compiles in my machine without problems. Try downloading the library files from the official repository (https://cefbuilds.com) and replacing them.

**Comment by fkpwolf** [comment]
the file Linux/lib/libcef.so is 32 bit, so...

**Comment by acristoffers** [comment]
True. I think I replaced it for a 64 bits in my Linux and forgot about it, or forgot to push it to the repository. I will take a look again at what I've done here and see if this repo got updated. Anyway, downloading the correct version of libcef should be up to the user, because this repo will get really huge if I keep updating it here. I'll write about it in the README too.
