### ISSUE TITLE
Why can i not run this porject

### ISSUE THREAD

**Issue by 244986830** [acristoffers/CEF3SimpleSample#14]
In windows, using visual studio 2013,when I run this project,  it cause a error:"Unhandled exception at 0x10CD1305 (libcef.dll) in CEF3SimpleSample.exe: 0xC0000005: Access violation reading location 0x00000000". what should i do to use it?

**Comment by acristoffers** [comment]
Try updating those libraries. I'm not keeping them up to date anymore, because this repo is already too big. Download the CEF library and compile the example to get new .dll and .lib files. Copy them to the right folder in this project. Also copy the include folder and replace.
You can get it here: http://opensource.spotify.com/cefbuilds/index.html
