### ISSUE TITLE
Error when build for MacOS

### ISSUE THREAD

**Issue by prsolucoes** [acristoffers/CEF3SimpleSample#15]
Hi,

Im getting error:
`'cassert' file not found`

![image](https://user-images.githubusercontent.com/395096/71849651-4bf65180-30b1-11ea-858e-10ff618c2ef7.png)

1 - Git clone your-repo
2 - Exec: `open CEF3SimpleSample.xcodeproj/`
3 - Run!

Im using macos catalina and xcode 11.

**Comment by acristoffers** [comment]
It seems that Apple no longer supports libstdc++ and prefers libc++, which requires changing the precompiled files shipped. I'm looking if newer versions of the cef_build has correct files.

**Comment by acristoffers** [comment]
A working version has been pushed. The issue was that of the standard library and after updating the framework I had to fix some code to conform to the new API (which didn't change much, though).

GitHub complained about file size, so the library file was compressed. You need to decompress it before running the project. From the root directory:

```bash
cd CEF3SimpleSample/CEF/Mac/lib/Chromium\ Embedded\ Framework.framework
tar -xf Chromium\ Embedded\ Framework.txz
```
