### ISSUE TITLE
Help GPUCache folder and Process running

### ISSUE THREAD

**Issue by JoongEyong** [acristoffers/CEF3SimpleSample#22]
Hello.

I have added this command to disable GPUCache folder, but doenst work, you have idea?
`command_line->AppendSwitch("disable-gpu-program-cache");`

And when I close the software, the program still running on process list, have you idea?

Thank you so much, your example is very good!

**Comment by acristoffers** [comment]
Hi @JoongEyong 

I have moved from CEF to Electron years ago. I keep the repository relatively up-to-date to help people, but I actually know very little about CEF. I never tried to fiddle with switches or cache.
Sorry, but I cannot help on that one :(

About it staying in the process list, you didn't say what operating system you're using, but I would say to look at why it is still open. Debug it to see where the main function is hanging.

**Comment by JoongEyong** [comment]
Hi @acristoffers , thank you for answer.

I'm doing a study and trying to build software that uses a browser style with cef, like spotify, discord and other programs that are similar, is Eletron better than cef?

I'm using Windows 10 last update.

**Comment by acristoffers** [comment]
It depends on what you want to do. Electron is much easier to use, in my opinion, but its low level is still javascript, not C/C++. If you don't need to do anything with C/C++ in your application then Electron is better. CEF gives you more control of the browser too. So it really depends on your needs.

If you are using Windows, you gotta see if your main application is quitting after you close all windows. If it leaves helper processes behind, it's an issue with CEF. If the main process is not exiting, it might be a problem in the example. Try running the application standalone, without an IDE, as it might be the IDE that is keeping the process open. Anyway, the path is to debug the main function to gather more information on when/why it's hanging.

**Comment by JoongEyong** [comment]
I just want to make a login screen in which my application download updates, it is very simple, the program downloads updates and goes back to the progress bar of html / js, do you have any example of Eletron?

Thank you again.

**Comment by acristoffers** [comment]
I don't have a simple example like this one for Electron, but it isn't necessary as they have great documentation at https://www.electronjs.org/docs.

I have a public project, but it is somewhat evolved. You can try to use it as a template, replacing my code by yours, but it would take you some time to understand how the project is setup. My setup was made work on Linux and macOS only, I can build for Windows from macOS, so no need for me to worry about Windows. Since you use Windows, it would mean rewriting my build scripts PowerShell. So I recommend you follow the documentation instead, and use my project as configuration reference.
https://github.com/acristoffers/Lachesis

**Comment by JoongEyong** [comment]
Thank you so much!
