### ISSUE TITLE
Enter the password every time you re-run the app

### ISSUE THREAD

**Issue by orientwhite** [acristoffers/CEF3SimpleSample#32]
After Xcode has finished running and started the application, the password is always required, and I have clicked Always allow

**Comment by orientwhite** [comment]
The app wants to use your confidential information stored in the "Chromium Safe Storage" of the keychain

**Comment by acristoffers** [comment]
Yes, because macOS resets the permission if anything changes in the app, which is the case whenever you build with Xcode. I'll try to see what the permission is for in the first place, since I don't use anything that requires it. It's probably something internal to CEF or some unnecessary info.plist entry.

**Comment by acristoffers** [comment]
Here is an (old) upstream issue on this: https://bitbucket.org/chromiumembedded/cef/issues/2692/mac-networkservice-allow-custom-service. The flag is now enabled by default and still not working. Passing the flag makes no difference either, so there is nothing I can do about it, it's a bug in CEF itself. You can just click deny, though and, as I said, in production, it will only be prompted once.
