### ISSUE TITLE
About ClientV8ExtensionHandler file

### ISSUE THREAD

**Issue by orientwhite** [acristoffers/CEF3SimpleSample#33]
In Xcode,Why do the target members of the ClientV8ExtensionHandler file need to be checked, so my business code also needs to be like this.

**Comment by acristoffers** [comment]
Sorry, but your text doesn't make sense.

**Comment by orientwhite** [comment]
In the mac project, the ClientV8Extension file needs to be compiled in 5 targets such as CEF3Simple,CEF3Simple(GPU) ,CEF3SimpleRender, etc.

**Comment by acristoffers** [comment]
Yes, unfortunately, macOS requires this repetition. In the other platforms, CEF can only call the same binary many times to do the job of each helper, which avoids this. You can see that this repetition is needed because the class ClientApp, which is also used in the helpers, depends on it. You may try to create another ClientApp class just for the helper, which does not depend on anything, but I'm not sure that your app will work in that case. I think we would not need to compile the helpers ourselves if they could have no link whatsoever if the main app.

**Comment by orientwhite** [comment]
How to exchange data between the main process and the rendering process

**Comment by acristoffers** [comment]
https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-inter-process-communication-ipc

**Comment by orientwhite** [comment]
Thank you so much
