### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ShelleyLake** [acristoffers/CEF3SimpleSample#37]
@acristoffers 

Thank you for your example for using the CEF framework.
If I understand correctly the example, a web page is displayed with (among other things) a button.

When the button is clicked, the code registered in `ClientApp::OnWebKitInitialized() `is executed, which in turn executes JavaScript code that then operates on the page itself.

Wouldn't you have the ability to supplement your example with an additional function?
mMy ability to understand CEF is quite limited, so I'm hoping for any help).

I would need to understand how a c++ function (and thus not something that starts from the "web" part) can execute Javascript code, specifically a Javascript function, and get the result from it.

For example a very trivial c++ function that sends a numeric value to a js function, which returns the same value multiplied by two.

Thanks for any help J.

**Comment by acristoffers** [comment]
No, when the button is clicked [ClientV8ExtensionHandler::Execute](https://github.com/acristoffers/CEF3SimpleSample/blob/master/CEF3SimpleSample/CrossPlatform/ClientV8ExtensionHandler.cpp#L27) is executed. `ClientApp::OnWebKitInitialized()` is executed as soon as the app launches and registers `ClientV8ExtensionHandler::Execute` to be executed when a function is called in the `app` javascript object.

Then what you asked for is in that function: it evaluates a javascript code in the browser side:

```c++
			std::string jscall = "ChangeText('";
			jscall += text;
			jscall += "');";
			frame->ExecuteJavaScript(jscall, frame->GetURL(), 0);
```

It's been a long time since I actually used CEF, but if I recall correctly you cannot block and wait for the response, you have to make so your C++ code calls the javascript code and then the javascript code will have to call a c++ function to get the result back. This `ExecuteJavaScript` is the way to start, since it executes javascript code.

**Comment by ShelleyLake** [comment]
thanks
